import { Type } from "./musical";

export const RUNNING_13 = {
  // 1-2-8
  '01-1': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 1-2-6
  '01-2': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 1-2-7
  '01-3': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 2-2-7
  '02-1': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 1-2-7
  '02-2': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 2-2-6
  '02-3': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-2-7
  '03-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-2-6
  '03-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-2-6
  '03-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 3-2-6
  '04-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-2-5
  '04-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 2-3-6
  '04-3': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-1-9
  '05-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-1-8
  '05-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-1-8
  '05-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 5-1-7
  '06-1': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 3-1-7
  '06-2': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 3-1-10
  '06-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 10-1-4
  '07-1A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 4-1-6
  '07-2A': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 5-1-7
  '07-3A': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 6-1-6
  '07-1B': [
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.END },
  ],
  // 4-1-6
  '07-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 4-1-8
  '07-3B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 10-1-4
  '08-1A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 3-1-7
  '08-2A': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 5-1-6
  '08-3A': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 5-1-7
  '08-1B': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 3-1-7
  '08-2B': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-1-12
  '08-3B': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 10-1, 15-1, 20-1, 10
  '09-1A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 15 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 20 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 5-1-6
  '09-2A': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 10-1-4
  '09-3A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 6-1-8
  '09-1B': [
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 6 },
    { type: Type.END },
  ],
  // 4-1-7
  '09-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 4-1-9
  '09-3B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 10-1, 20-1, 30
  '10-1A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 20 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 30 },
    { type: Type.END },
  ],
  // 10-1-4
  '10-2A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 20-1, 15-1, 10
  '10-3A': [
    { type: Type.RUNNING, num: 20 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 15 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 8-1-7
  '10-1B': [
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.END },
  ],
  // 4-1-9
  '10-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 5-1-8
  '10-3B': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 40-1, 20
  '11-1A': [
    { type: Type.RUNNING, num: 40 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 20 },
    { type: Type.END },
  ],
  // 10-1-4
  '11-2A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 20-1, 15-1, 10
  '11-3A': [
    { type: Type.RUNNING, num: 20 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 15 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 10-1-6
  '11-1B': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 4-1-9
  '11-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 5-1-8
  '11-3B': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 50
  '12-1A': [
    { type: Type.RUNNING, num: 50 },
    { type: Type.END },
  ],
  // 10-1-3
  '12-2A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 15-1-2, 10
  '12-3A': [
    { type: Type.RUNNING, num: 15 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 15 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 8-1-6
  '12-1B': [
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 8 },
    { type: Type.END },
  ],
  // 4-1-6
  '12-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
  // 5-1-7
  '12-3B': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 40
  '13-1A': [
    { type: Type.RUNNING, num: 40 },
    { type: Type.END },
  ],
  // 10-1-3
  '13-2A': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 10-1-4
  '13-1B': [
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 10 },
    { type: Type.END },
  ],
  // 4-1-6
  '13-2B': [
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 4 },
    { type: Type.END },
  ],
}
