import { Type } from "./musical";

export const RUNNING_13 = {
  // 1-2-8
  '01-1': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 1-2-6
  '01-2': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 1-2-7
  '01-3': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 2-2-7
  '02-1': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 1-2-7
  '02-2': [
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 1 },
    { type: Type.END },
  ],
  // 2-2-6
  '02-3': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-2-7
  '03-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-2-6
  '03-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-2-6
  '03-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 3-2-6
  '04-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-2-5
  '04-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 2 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 2-3-6
  '04-3': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 3 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-1-9
  '05-1': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 2-1-8
  '05-2': [
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 2 },
    { type: Type.END },
  ],
  // 3-1-8
  '05-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 5-1-7
  '06-1': [
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 5 },
    { type: Type.END },
  ],
  // 3-1-7
  '06-2': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
  // 3-1-10
  '06-3': [
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.WALKING, num: 1 },
    { type: Type.RUNNING, num: 3 },
    { type: Type.END },
  ],
}
